version: "3.7"
services:
  db:
    container_name: "todo-app-db"
    image: "postgres:11.5"
    ports:
    - 5432:5432
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=quarkus_todo
