server:
  port: 8090
spring:
  profiles:
    active: dev
  jackson:
    serialization:
      write-dates-as-timestamps: false


---

spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    platform: h2
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${SPRING_TODO_DB:spring_todo}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
    initialization-mode: always

